services:
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager

    restart: unless-stopped

    mem_limit: 128m
    cpus: "0.5"

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    ports:
      - "9093:9093"

    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro

    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"

    networks:
      - monitoring

networks:
  monitoring:
    external: true
