apiVersion: v1
kind: Service
metadata:
  name: otel-demo
  namespace: otel-demo

spec:
  selector:
    app: otel-demo

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: ClusterIP
