services:
  otel-demo:
    build: .
    container_name: otel-demo
    restart: unless-stopped

    mem_limit: 256m
    cpus: "0.5"

    ports:
      - "5000:5000"

    networks:
      - monitoring

networks:
  monitoring:
    external: true
